apiVersion: v1
kind: Service
metadata:
  name: golangweb
  labels:
    app: golangweb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: golangweb.yourdomain.com
spec:
  type: LoadBalancer #Clusterip for internal LoadBalancer for external
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: golangweb